per_listener_settings true

persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type error
log_type warning
log_type notice

# Réseau Docker interne uniquement : Hub + simulateur.
listener 1883 0.0.0.0
protocol mqtt
allow_anonymous true

# Accès terrain ESP32 depuis Internet.
listener 8883 0.0.0.0
protocol mqtt
allow_anonymous false
password_file /mosquitto/secrets/passwords
acl_file /mosquitto/secrets/acl
certfile /mosquitto/certs/fullchain.pem
keyfile /mosquitto/certs/privkey.pem
tls_version tlsv1.2
require_certificate false
