services:
  mqtt:
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/mosquitto.vps.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/secrets:/mosquitto/secrets:ro
      - ./mosquitto/certs:/mosquitto/certs:ro
